test_framework: junit

project:
  scala_version: 2.8.0.RC2
  ant_version: 1.7.1
  ivy_version: 2.1.0
  package_type: war
  plugin_resources: ".brzy/plugins"
  plugin_repository: http://www.brzy.org/nexus/content/repositories/releases

views:
  name: brzy-scalate
  org: org.brzy
  version: "0.2"
  config_class: org.brzy.plugin.ScalatePluginConfig
  file_extension: ".ssp"
  html_version: html5

repositories:
  - id: brzy
    name: brzy
    url: http://brzy.org/nexus/content/repositories/releases
  - id: java-net2
    name: java-net2
    url: http://download.java.net/maven/2
  - id: scala-tools
    name: scala-tools
    url: http://scala-tools.org/repo-releases
  - id: jboss
    name: jboss
    url: http://repository.jboss.com/maven2

dependencies:
  - {conf: builder, org: org.jyaml, name: jyaml, rev: "1.3"}
  - {conf: builder, org: org.slf4j, name: slf4j-simple, rev: "1.5.11"}
  - {conf: builder, org: org.brzy, name: brzy-shell, rev: "0.1"}
  - {conf: builder, org: xerces, name: xerces, rev: "2.4.0"}
  - {conf: "compile,builder", org: org.brzy, name: brzy-config, rev: "0.1"}
  - {conf: "compile,builder", org: org.brzy, name: brzy-mvc, rev: "0.1"}
  - {conf: "compile,builder", org: org.scala-lang, name: scala-compiler, rev: "2.8.0.RC2"}
  - {conf: "compile,builder", org: org.scala-lang, name: scala-library, rev: "2.8.0.RC2"}
  - {conf: "compile,builder", org: org.slf4j, name: slf4j-api, rev: "1.5.11"}
  - {conf: compile, org: javassist, name: javassist, rev: "3.11.0.GA"}
  - {conf: compile, org: org.aspectj, name: aspectjweaver, rev: "1.6.8"}
  - {conf: compile, org: javassist, name: javassist, rev: "3.11.0.GA"}
  - {conf: compile, org: org.aspectj, name: aspectjweaver, rev: "1.6.8"}
  - {conf: compile, org: ch.qos.logback, name: logback-classic, rev: "0.9.20"}
  - {conf: compile, org: org.jyaml, name: jyaml, rev: "1.3"}
  - {conf: compile, org: commons-lang, name: commons-lang, rev: "2.5"}
  - {conf: test, org: junit, name: junit, rev: "4.7"}

web_xml:
 - context-param: { param-name : brzy-env, param-value: development}
 - listener: {listener-class: org.brzy.application.WebAppListener}
 - filter: {filter-name: BrzyFilter, filter-class: org.brzy.action.Filter}
 - filter-mapping: {filter-name: BrzyFilter, url-pattern: "/*"}
 - servlet: { servlet-name: BrzyServlet, servlet-class: org.brzy.action.Servlet, load-on-startup: "1"}
 - servlet-mapping: { servlet-name: BrzyServlet, url-pattern: "*.brzy"}
 - welcome-file-list: { welcome-file: index.brzy}
 - error-page: { error-code: "404", location: /error-404.ssp}
 - error-page: { error-code: "500", location: /error-500.ssp}
 - error-page: {exception-type: java.lang.Throwable, location: /error-500.ssp}

